export const pluginRegistry = {
  metamod: {
    name: 'Metamod:Source',
    currentVersion: '2.0.0-git1386',
    folderName: 'metamod',
    category: 'core' as const,
    tags: ['core', 'framework'],
    description: 'Base framework for all server mods',
    downloadUrl: 'https://mms.alliedmods.net/mmsdrop/2.0/',
  },
  cssharp: {
    name: 'CounterStrikeSharp',
    currentVersion: '1.0.363',
    folderName: 'CounterStrikeSharp',
    category: 'core' as const,
    tags: ['core', 'scripting'],
    description: 'C# scripting platform for CS2',
    githubRepo: 'roflmuffin/CounterStrikeSharp',
  },
  // MetaMod Plugins
  cs2fixes: {
    name: 'CS2Fixes',
    currentVersion: '1.17.1',
    folderName: 'cs2fixes',
    category: 'metamod' as const,
    tags: ['fix', 'utility', 'performance'],
    description: 'Essential fixes and performance improvements',
    githubRepo: 'p0iss0n/cs2fixes',
  },
  playerfix: {
    name: 'ServerListPlayersFix',
    currentVersion: '1.0.6',
    folderName: 'ServerListPlayersFix',
    category: 'metamod' as const,
    tags: ['fix', 'utility'],
    description: 'Fixes players count in server browser',
  },
  movelock: {
    name: 'MovementUnlocker',
    currentVersion: '1.10',
    folderName: 'MovementUnlocker',
    category: 'metamod' as const,
    tags: ['movement', 'surf', 'bhop'],
    description: 'Removes max speed limitation (BHOP/Surf)',
  },
  multiaddonmanager: {
    name: 'MultiAddonManager',
    currentVersion: '1.4.10',
    folderName: 'multiaddonmanager',
    category: 'metamod' as const,
    tags: ['utility', 'workshop'],
    description: 'Manage multiple workshop addons',
  },
  accelerator: {
    name: 'AcceleratorCS2',
    currentVersion: '2.0.5',
    folderName: 'AcceleratorCS2',
    category: 'metamod' as const,
    tags: ['fix', 'utility', 'debug'],
    description: 'Generate crash dumps on server crash',
  },
  // CS# Plugins
  matchzy: {
    name: 'MatchZy',
    currentVersion: '0.8.15',
    folderName: 'MatchZy',
    category: 'cssharp' as const,
    tags: ['gamemode', 'competitive', 'admin'],
    description: 'Comp/Match management plugin',
    githubRepo: 'shaneis/MatchZy',
  },
  simpleadmin: {
    name: 'CS2-SimpleAdmin',
    currentVersion: '1.7.8-beta-10b1',
    folderName: 'CS2-SimpleAdmin',
    category: 'cssharp' as const,
    tags: ['admin', 'utility'],
    description: 'User-friendly admin management system',
  },
  weaponpaints: {
    name: 'WeaponPaints',
    currentVersion: 'latest',
    folderName: 'WeaponPaints',
    category: 'cssharp' as const,
    tags: ['fun', 'skins'],
    description: 'Skins, Gloves, and Agents changer',
  },
  retakes: {
    name: 'CS2-Retake',
    currentVersion: '3.0.2',
    folderName: 'RetakesPlugin',
    category: 'cssharp' as const,
    tags: ['gamemode', 'retakes', 'competitive'],
    description: 'Retake gamemode implementation',
  },
  ranks: {
    name: 'CS2-Ranks',
    currentVersion: 'latest',
    folderName: 'CS2-Ranks',
    category: 'cssharp' as const,
    tags: ['fun', 'utility', 'ranking'],
    description: 'XP and Rank system (Global Elite)',
  },
  rtv: {
    name: 'RockTheVote',
    currentVersion: '1.9.5',
    folderName: 'RockTheVote',
    category: 'cssharp' as const,
    tags: ['utility', 'map-voting'],
    description: 'Map voting and management system',
    githubRepo: 'Oz-Lin/cs2-rockthevote',
  },
  essentials: {
    name: 'CS2-Essentials',
    currentVersion: '1.3.0',
    folderName: 'CS2-Essentials',
    category: 'cssharp' as const,
    tags: ['utility', 'admin', 'commands'],
    description: 'Basic commands and exploit fixes',
  },
  botai: {
    name: 'BotAI',
    currentVersion: '1.3',
    folderName: 'BotAI',
    category: 'cssharp' as const,
    tags: ['bot', 'utility', 'ai'],
    description: 'Improved Bot AI (prevents knife rushing, smarter behavior)',
  },
  fixrandomspawn: {
    name: 'FixRandomSpawn',
    currentVersion: '1.1.4.1',
    folderName: 'FixRandomSpawn',
    category: 'cssharp' as const,
    tags: ['fix', 'utility', 'spawn'],
    description: 'Fixes mp_randomspawn ConVar for any game mode',
  },
  execafter: {
    name: 'CS2_ExecAfter',
    currentVersion: '1.0.0',
    folderName: 'CS2_ExecAfter',
    category: 'cssharp' as const,
    tags: ['utility', 'admin', 'commands'],
    description: 'Executes commands after server events or delay',
  },
  weaponrestrict: {
    name: 'WeaponRestrict',
    currentVersion: '26.01.3',
    folderName: 'WeaponRestrict',
    category: 'cssharp' as const,
    tags: ['utility', 'weapons', 'restriction'],
    description: 'Restrict specific weapons per team or globally',
  },
  removemapweapons: {
    name: 'CS2 Remove Map Weapons',
    currentVersion: '1.0.1',
    folderName: 'CS2-Remove-Map-Weapons',
    category: 'cssharp' as const,
    tags: ['utility', 'fix', 'weapons'],
    description: 'Removes manually placed weapons from maps',
  },
  gamemodemanager: {
    name: 'GameModeManager',
    currentVersion: '1.0.63',
    folderName: 'GameModeManager',
    category: 'cssharp' as const,
    tags: ['gamemode', 'admin', 'utility'],
    description: 'Manage game modes and map groups easily',
  },
  inventorysim: {
    name: 'Inventory Simulator',
    currentVersion: '37',
    folderName: 'InventorySimulator',
    category: 'cssharp' as const,
    tags: ['fun', 'skins', 'inventory'],
    description: 'Skin changer (Skins, Gloves, Agents, etc)',
  },
  modelchanger: {
    name: 'PlayerModelChanger',
    currentVersion: '1.8.6',
    folderName: 'PlayerModelChanger',
    category: 'cssharp' as const,
    tags: ['fun', 'skins', 'models'],
    description: 'Lightweight player model changer',
  },
  mapconfigurator: {
    name: 'MapConfigurator',
    currentVersion: '1.0.2',
    folderName: 'MapConfigurator',
    category: 'cssharp' as const,
    tags: ['utility', 'admin', 'map-config'],
    description: 'Unique configuration files for each map',
  },
  damageinfo: {
    name: 'K4-DamageInfo',
    currentVersion: '2.4.0',
    folderName: 'K4-DamageInfo',
    category: 'cssharp' as const,
    tags: ['utility', 'combat', 'hud'],
    description: 'Detailed damage and hit group information',
  },
  cs2rcon: {
    name: 'CS2Rcon',
    currentVersion: '1.2.0',
    folderName: 'CS2Rcon',
    category: 'cssharp' as const,
    tags: ['admin', 'utility', 'rcon'],
    description: 'Rudimentary RCON implementation via CSS',
  },
  sharptimer: {
    name: 'SharpTimer',
    currentVersion: '0.3.1x',
    folderName: 'SharpTimer',
    category: 'cssharp' as const,
    tags: ['gamemode', 'timer', 'movement', 'surf', 'bhop'],
    description: 'Timer for Surf/KZ/Bhop/MG/Deathrun',
  },
  stfixes: {
    name: 'STFixes',
    currentVersion: '1.0.5',
    folderName: 'STFixes',
    category: 'cssharp' as const,
    tags: ['fix', 'utility', 'movement'],
    description: 'Common fixes for SharpTimer servers',
  },
  arenas: {
    name: 'K4-Arenas',
    currentVersion: '2.0.8',
    folderName: 'K4-Arenas',
    category: 'cssharp' as const,
    tags: ['gamemode', 'arenas', 'ladder'],
    description: 'Multi-arena/Ladder gamemode',
  },
  instadefuse: {
    name: 'CS2 Instadefuse',
    currentVersion: '2.0.0',
    folderName: 'cs2-instadefuse',
    category: 'cssharp' as const,
    tags: ['utility', 'gamemode', 'bomb'],
    description: 'Instant bomb defusal when safe',
  },
  retakesallocator: {
    name: 'CS2 Retakes Allocator',
    currentVersion: '2.4.2',
    folderName: 'cs2-retakes-allocator',
    category: 'cssharp' as const,
    tags: ['gamemode', 'retakes', 'weapons'],
    description: 'Advanced weapon allocator for Retakes',
  },
  whitelist: {
    name: 'CS2 Whitelist',
    currentVersion: '1.0.0',
    folderName: 'WhiteList',
    category: 'cssharp' as const,
    tags: ['admin', 'security', 'utility'],
    description: 'Restrict access to specific SteamIDs',
  },
  executes: {
    name: 'CS2 Executes',
    currentVersion: '1.1.1',
    folderName: 'cs2-executes',
    category: 'cssharp' as const,
    tags: ['gamemode', 'executes', 'competitive'],
    description: 'Execute site takes gamemode',
  },
  advertisement: {
    name: 'CS2 Advertisement',
    currentVersion: '1.0.8-recompile',
    folderName: 'Advertisement',
    category: 'cssharp' as const,
    tags: ['utility', 'ads'],
    description: 'Show ads in chat/center/panel',
  },
  deathmatch: {
    name: 'CS2 Deathmatch',
    currentVersion: '1.3.0',
    folderName: 'Deathmatch',
    category: 'cssharp' as const,
    tags: ['gamemode', 'deathmatch'],
    description: 'Custom Deathmatch with gun selection',
  },
  prefireprac: {
    name: 'OpenPrefirePrac',
    currentVersion: '0.1.47',
    folderName: 'OpenPrefirePrac',
    category: 'cssharp' as const,
    tags: ['gamemode', 'practice', 'prefire'],
    description: 'Prefire practice on competitive maps',
  },
  customvotes: {
    name: 'CS2-CustomVotes',
    currentVersion: '1.1.4',
    folderName: 'CS2-CustomVotes',
    category: 'cssharp' as const,
    tags: ['utility', 'votes', 'admin'],
    description: 'Create custom votes for settings',
  },
  deathrun: {
    name: 'deathrun-manager',
    currentVersion: '0.5.1',
    folderName: 'deathrun-manager',
    category: 'cssharp' as const,
    tags: ['gamemode', 'deathrun'],
    description: 'Deathrun gamemode manager',
  },
  announcement: {
    name: 'AnnouncementBroadcaster',
    currentVersion: '0.5',
    folderName: 'CS2AnnouncementBroadcaster',
    category: 'cssharp' as const,
    tags: ['utility', 'announcement', 'chat'],
    description: 'Conditional messages and timer broadcasts',
  },
  jRandomSkills: {
    name: 'jRandomSkills',
    currentVersion: '1.0.4',
    folderName: 'jRandomSkills',
    category: 'cssharp' as const,
    tags: ['fun', 'gamemode'],
    description: 'Random gameplay modifiers every round',
  },
  rtd: {
    name: 'RollTheDice',
    currentVersion: '26.01.3',
    folderName: 'cs2-roll-the-dice',
    category: 'cssharp' as const,
    tags: ['fun', 'gamemode', 'rtd'],
    description: 'Roll dice for random effects',
  },
  mutualscoring: {
    name: 'CS2-MutualScoringPlayers',
    currentVersion: '1.0.3',
    folderName: 'MutualScoringPlayers',
    category: 'cssharp' as const,
    tags: ['utility', 'combat', 'scoring'],
    description: 'Track head-to-head kills between players',
  },
  warcraft: {
    name: 'CS2WarcraftMod',
    currentVersion: '3.3.5',
    folderName: 'warcraft-plugin',
    category: 'cssharp' as const,
    tags: ['gamemode', 'rpg', 'warcraft'],
    description: 'Comprehensive Warcraft RPG system',
  },
  advancedweapon: {
    name: 'Advanced Weapon System',
    currentVersion: '1.11',
    folderName: 'AdvancedWeaponSystem',
    category: 'cssharp' as const,
    tags: ['utility', 'combat', 'weapons'],
    description: 'Advanced weapon attribute control',
  },
  oneinthechamber: {
    name: 'CS2 One In The Chamber',
    currentVersion: '1.0.0',
    folderName: 'cs2-OneInTheChamber',
    category: 'cssharp' as const,
    tags: ['gamemode', 'one-in-the-chamber'],
    description: 'One In The Chamber gamemode',
  },
  quakesounds: {
    name: 'CS2 Quake Sounds',
    currentVersion: '26.01.3',
    folderName: 'QuakeSounds',
    category: 'cssharp' as const,
    tags: ['fun', 'audio', 'quake'],
    description: 'Quake announcment sounds for kills',
  },
  weaponspeed: {
    name: 'CS2-WeaponSpeed',
    currentVersion: '1.3',
    folderName: 'WeaponSpeed',
    category: 'cssharp' as const,
    tags: ['fun', 'utility', 'speed'],
    description: 'Speed boost when firing specific weapons',
  },
  spectatorlist: {
    name: 'SpectatorList-CS2',
    currentVersion: '1.0.5',
    folderName: 'SpectatorList',
    category: 'cssharp' as const,
    tags: ['utility', 'hud', 'spectator'],
    description: 'Shows real-time spectators on screen',
  },
  football: {
    name: 'SLAYER_Football',
    currentVersion: '1.1',
    folderName: 'SLAYER_Football',
    category: 'cssharp' as const,
    tags: ['gamemode', 'fun', 'football'],
    description: 'Football game mode for CS2',
  },
  revive: {
    name: 'SLAYER_Revive',
    currentVersion: '1.3.2',
    folderName: 'SLAYER_Revive',
    category: 'cssharp' as const,
    tags: ['gamemode', 'utility', 'revive'],
    description: 'Revive teammates in-game',
  },
  teleportkill: {
    name: 'CS2-TeleportKill',
    currentVersion: '1.0.1',
    folderName: 'TeleportKill',
    category: 'cssharp' as const,
    tags: ['fun', 'utility', 'teleport'],
    description: 'Teleport to victim position on kill',
  },
  menumanager: {
    name: 'MenuManager',
    currentVersion: '1.4.1',
    folderName: 'MenuManager',
    category: 'cssharp' as const,
    tags: ['utility', 'menu', 'library'],
    description: 'Advanced menu management system for CS2',
  },
  playersettings: {
    name: 'PlayerSettings',
    currentVersion: '0.9.3',
    folderName: 'PlayerSettings',
    category: 'cssharp' as const,
    tags: ['utility', 'settings', 'persistence'],
    description: 'Persistent player settings and preferences',
  },
  anybaselib: {
    name: 'AnyBaseLib',
    currentVersion: '0.9.4',
    folderName: 'AnyBaseLib',
    category: 'cssharp' as const,
    tags: ['library', 'utility', 'core'],
    description: 'Base library for NickFox007 plugins',
  },
  afkmanager: {
    name: 'AFKManager',
    currentVersion: '0.2.8',
    folderName: 'AFKManager',
    category: 'cssharp' as const,
    tags: ['utility', 'afk', 'management'],
    description: 'Detects and manages AFK players (kick/move to spec)',
  },
  antirush: {
    name: 'AntiRush',
    currentVersion: '2.0.3',
    folderName: 'AntiRush',
    category: 'cssharp' as const,
    tags: ['utility', 'rush', 'management'],
    description: 'Defines and manages rush/camp zones on maps',
  },
  autobalance: {
    name: 'AutoBalance',
    currentVersion: '1.0.0',
    folderName: 'AutoBalance',
    category: 'cssharp' as const,
    tags: ['utility', 'balance', 'teams'],
    description: 'Automatically balances teams based on player count',
  },
  mappropads: {
    name: 'MapPropAds',
    currentVersion: '1.0.0',
    folderName: 'CS2-Poor-MapPropAds',
    category: 'cssharp' as const,
    tags: ['utility', 'ads', 'visual'],
    description: 'Create billboard-type advertisements on map props',
  },
  quatrixmapconfig: {
    name: 'QuatrixMapConfig',
    currentVersion: '1.0.8',
    folderName: 'QuatrixMapConfig',
    category: 'cssharp' as const,
    tags: ['utility', 'map-config', 'automation'],
    description: 'Advanced map-specific configuration loader for Quatrix',
  },
  infotop: {
    name: 'InfoTop',
    currentVersion: '1.0.0',
    folderName: 'InfoTop',
    category: 'cssharp' as const,
    tags: ['utility', 'info', 'hud'],
    description: 'Displays key server information on HUD',
  },
} as const;

export type PluginId = keyof typeof pluginRegistry;
