export const COMMON_COMMANDS = [
  // --- Essential Server Info ---
  'status',
  'stats',
  'tv_status',
  'meta list',
  'meta version',
  'css_plugins list',

  // --- CS2-SimpleAdmin (Plugin Commands) ---
  'css_who ',
  'css_players',
  'css_ban ',
  'css_addban ',
  'css_banip ',
  'css_unban ',
  'css_kick ',
  'css_gag ',
  'css_addgag ',
  'css_unmute ',
  'css_mute ',
  'css_addmute ',
  'css_give ',
  'css_strip ',
  'css_hp ',
  'css_speed ',
  'css_gravity ',
  'css_money ',
  'css_god ',
  'css_slay ',
  'css_slap ',
  'css_vote ',
  'css_map ',
  'css_wsmap ',
  'css_asay ',
  'css_say ',
  'css_psay ',
  'css_csay ',
  'css_hsay ',
  'css_noclip ',
  'css_freeze ',
  'css_unfreeze ',
  'css_respawn ',
  'css_cvar ',
  'css_rcon ',

  // --- Map & Match Control ---
  'map ',
  'changelevel ',
  'host_workshop_map ',
  'mp_restartgame 1',
  'mp_warmup_start',
  'mp_warmup_end',
  'mp_pause_match',
  'mp_unpause_match',
  'mp_roundtime ',
  'mp_freezetime ',
  'mp_maxrounds ',
  'mp_halftime ',
  'mp_c4timer ',

  // --- Bot Management ---
  'bot_add',
  'bot_kick',
  'bot_quota ',
  'bot_difficulty ',
  'bot_stop ',

  // --- Core Server Settings ---
  'sv_cheats ',
  'sv_gravity ',
  'sv_infinite_ammo ',
  'sv_alltalk ',
  'sv_full_alltalk ',
  'sv_password ',
  'hostname ',
  'sv_maxplayers ',
  'sv_lan ',

  // --- Plugin Management ---
  'meta refresh',
  'css_plugins reload ',
  'css_plugins load ',
  'css_plugins unload ',
  'exec ',
].sort();

export const NOISE_PATTERNS = [
  // --- Admin & Panel RCON Queries (Frequent Noise) ---
  /rcon from ".*": command "status"/,
  /rcon from ".*": command "css_players"/,
  /rcon from ".*": command "log on"/,
  /rcon from ".*": command "sv_logecho 1"/,
  /rcon from ".*": command "sv_logfile 0"/,
  /rcon from ".*": command "sv_logbans 1"/,
  /command "(status|css_players|log on|sv_logecho 1|sv_logfile 0|sv_logbans 1)"/, // Catch split lines
  /.*rcon from ".*[:"]?$/, // Catch fragmented RCON from lines
  /from ".*": command ".+"/, // General RCON from lines
  /: rcon$/, // First line of split RCON

  // --- Engine & Resource Warnings (No user action possible) ---
  /sequence\/animation name collision found/,
  /ResourceHandleToData.*failed! Falling back to error texture!/,
  /texturebase.cpp.*failed! Falling back to error texture!/,
  /.*Long frame .*/,
  /Giving up attempts to make more random spawn points./,
  'CNavGenParams - Nav mesh requests project default generation parameters',
  'Failed loading resource "maps/prefabs/misc/terrorist_team_intro_variant2/world_visibility.vvis_c"',

  // --- CS2-SimpleAdmin Plugin Specific Noise ---
  /Registering command: .* with aliases: .*/,
  /Registering custom command: .*/,
  /Loaded server with ip .*/,
  /Finished loading plugin .*/,
  /Loading plugin .*/,
  /\[Info\] - Trampoline - .*/,
  /Event System loaded .* events from file: .*/,
  /'.*' took .*ms to execute \d+ commands, backlog is \d+ commands/,
  'Server logging enabled.',
  /L \d{2}\/\d{2}\/\d{4} - \d{2}:\d{2}:\d{2}: server_cvar: .*/,
  /JSON_BEGIN\{/,
  /JSON_END/,
  /".*": ".*",/, // JSON content lines
  /".*": {/,
  /MatchStatus: .*/,
  /GC Connection established .*/,
  /\[STARTUP\] .* activated session on GC/,
  /OnPreResetRound => CTMDBG/,
  /willSwitch \d+ \d+\.\d+/,
  /Using spawn points configuration .*/,

  // --- Other System Noise ---
  'GameTypes: missing mapgroupsSP entry',
  'Entry player was not found in surfaceproperties_footsteps.txt',

  // --- Source 2 / CS2 Engine Startup & Technical Noise ---
  /CEntitySystem::BuildEntityNetworking .*/,
  /\[STARTUP\] .* (server module init ok|created game rules)/,
  /CHostStateMgr::QueueNewRequest.*/,
  /HostStateRequest::Start.*/,
  /SwitchToLoop .* requested.*/,
  /Host activate: .*/,
  /Source2Init OK/,
  /Steam(GameServer_Init|Internal_SetMinidumpSteamID).*/,
  /Setting breakpad minidump .*/,
  /Looking up breakpad interfaces .*/,
  /Calling BreakpadMiniDumpSystemInit/,
  /\[S_API FAIL\].*/,
  /SDR RelayNetworkStatus: .*/,
  /AuthStatus \(.*\): .*/,
  /Initializing CSGO VScript Game System/,
  /SV:\s*(Executing server defaults|Executing dedicated server config file|Level loading started|CGameRulesGameSystem::GameInit|30 player server started|Connection to Steam servers successful|Spawn Server: .*)/,
  /LoadResponseSystem .*/,
  /CResponseSystem: .*/,
  /CPlayerVoiceListener::GameInit\(\)/,
  /execing (server_default|server|gamemode_competitive)\.cfg/,
  /exec: couldn't exec .*/,
  /Unknown command '.*'!/,
  /Got SDR network config\. .*/,
  /CWorldRendererMgr::ServiceWorldRequests long frame: .*/,
  /Gameserver logged on to Steam .*/,
  /Set SteamNetworkingSockets P2P_STUN_ServerList .*/,
  /CSource2Server::ApplyGameSettings game settings payload received:.*/,
  /::ExecGameTypeCfg \{/,
  /CNetworkGameServerBase::SetServerState .*/,
  /SV:\s*.*IGameSystem::LoopActivateAllSystems .*/,
  /HO:\s*.*IGameSystem::LoopActivateAllSystems.*/,
  /Created physics for .*/,
  /used during construction differ from defaults\. Please re-export the map\./,
  /ClientPutInServer create new player controller .*/,
  /\[.*\] cl_interp_ratio='', LerpTime=0/,
  'SV:  VAC secure mode is activated.',
  "Setting mapgroup to 'mg_active'",
  'Loading map "de_dust2"',

  // --- Map Settings Block (Non-JSON) ---
  /^(map|launchoptions|ct_models|t_models|maplist)\s*\{/,
  /^(mapname|levelname|mode|loadmap|changelevel|mapgroup|requires_attr|numSlots|c_game_type|c_game_mode|default_game_type|default_game_mode|ct_arms|t_arms|ctm_|tm_|de_).*/,
  /^\}$/,
  /L \d{2}\/\d{2}\/\d{4} - \d{2}:\d{2}:\d{2}: Started: {2}"".*/,
  /^-{5,}$/, // Match separator lines like ---------------
  /^Path ID:\s+File Path:$/,
  /^(ADDONS|CONTENT|CONTENTADDONS|CONTENTROOT|DEFAULT_WRITE_PATH|EXECUTABLE_PATH|GAME|GAMEBIN|GAMEROOT|MOD|OFFICIAL_ADDO|PLATFORM|SHADER_SOURCE|SHADER_SOURCE_MOD|SHADER_SOURCE_ROOT)\s+".*"/,
  /^(command line arguments|protected command line arguments \(stripped from above\)):/,
  /^-dedicated -console -usercon .*/,
  /^\+rcon_password <protected>$/,
  /^(Using breakpad crash handler|Forcing breakpad minidump interfaces to load|Console initialized|Steam AppId.*|InitSteamLogin_Internal.*|Steam Universe is invalid.*|ResetBreakpadAppId.*|Visibility enabled|USRLOCAL path not found|Trying to set dxlevel.*|Network System Initialized|MOD desires lightbinner GPU.*|Physics Console Communications is not initialized|reward_drop_list int.*|CSource2Server::GameServerSteamAPIActivated|\[S_API\] SteamAPI_Init|Steam Universe valid after having been requested when invalid)/,
  /^(CL: {2}CLoopModeLevelLoad|Logging into Steam gameserver account|CNetworkSystem::InitGameServer|Initialized low level socket|Created poll group|Network socket 'server' opened|GameTypes: could not find matching game mode|SV:\s*(maxplayers set to|ServerSteamID=)|\[STARTUP\].*logged on to Steam|Gameserver logged on to Steam|Certificate expires in|map de_dust2)/,
  /^(Accepting Steam Net connection|Sending S2C_CHALLENGE|Receiving C2S_CONNECT|CNetworkGameServerBase::ConnectClient|CServerSideClientBase::Connect|Client \d+ .* signon state|Sending S2C_CONNECTION|Client #\d+ .* connected|\[.*\] cl_interp_ratio=.*|SV:\s*.*STEAM USERID validated|SV: {2}Sending full update to client|Netchan queued message new high water mark|Removing Steam Net Connection).*/,
  /L \d{2}\/\d{2}\/\d{4} - \d{2}:\d{2}:\d{2}: ".*<.*><BOT><.*>".*/, // Bot connectivity
  /L \d{2}\/\d{2}\/\d{4} - \d{2}:\d{2}:\d{2}: ".*<.*><BOT>" switched from team .*/, // Bot team change
  /".*<.*><BOT><.*>" ChangeTeam\(\) CTMDBG .*/, // Bot team change internal
  /L \d{2}\/\d{2}\/\d{4} - \d{2}:\d{2}:\d{2}: (World triggered|Starting Freeze period)/,
  /L \d{2}\/\d{2}\/\d{4} - \d{2}:\d{2}:\d{2}: "(round_number|score_t|score_ct|map|server|fields|players|player_\d+)".*/, // Stats blocks
  /Model models\/.*: sequence\/animation name collision found .*/,
  /Model models\/.*\.v/, // Generic model loading

  // --- CleanerCS2 / Aggressive Noise Filter (Optimization) ---
  /.*UNEXPECTED LONG FRAME DETECTED.*/,
  /.*weapon services didn't find a shoot position.*/,
  /sv: Player tick from command clamped by server.*/,
  /sv: Lag comp - .*/,
  /sv: Running lag compensation for player.*/,
  /RemoveArrayElementsOutsideOfArrayMetadataBounds.*/,
  /Excessive frame time.*/,
  /sv tick = .*/,
  /.*Timing.*Performance.*/,
  /.*NetChan.*/,
  /.*(Receiving|Sending).*(NetChan|reliable|unreliable).*/,
  /.*NETWORK_DISCONNECT_.*/,
  /.*CloseSteamNetConnection.*/,
  /.*Summary of connection.*/,
  /.*Lag comp.*/,
  /.*cl_.*tick.*/,
  /will\s*switch\s*\d+\s*\d+\.\d+/,
  /.* (\d+ ticks, \d+\.\.\d+|elapsed, .* sim time, \d+ ticks|ms sim time, \d+ ticks)/,
  /SteamNetworkingSockets lock held for .*/,
  /This is usually a symptom of a general performance problem such as thread starvation/,
  /\[Data\] Ignored bad .* Stray data packet from host with no connection/,
];
